### ISSUE TITLE
Support for tcpSet.do

### ISSUE THREAD

**Issue by mjdyson** [ealse/GrowattApi#1]
Hello, have you been able to successfully control the inverter through your script? I'm looking to turn off the battery discharge (set discharge rate to 0%) when an EV is connected to the house load. It would likely need a script that runs on a home automation server that polls the car charger and then adjusts the inverter accordingly.

I've been able to track this down to tcpSet.do and some specific actions/parameters are used. I'm not a software guy but your code looks like it might be able to fit this in.

**Comment by mjdyson** [comment]
Hello again. I think I'll close this. I've found a PR into PyPi_GrowattServer that has this all built in.

[indykoning/PyPi_GrowattServer#19](https://github.com/indykoning/PyPi_GrowattServer/pull/19)

**Comment by ealse** [comment]
Glad you managed to solve it. Yesterday I briefly checked whether it was easy to add. It didn't seem like a problem in itself, although there were several actions that could be called. But it would be a bit more difficult to test, since I don't have such a system myself.
