### ISSUE TITLE
Login not working anymore

### ISSUE THREAD

**Issue by panuoksala** [ealse/GrowattApi#2]
Library is unable to make any calls, because login fails. I think they have changed the login url to
newTwoLoginApi.do

Could you update the login url + maybe change to login url to configurable, so we don't need to use hardcoded login urls.

**Comment by panuoksala** [comment]
https://powerforum.co.za/topic/11621-raw-access-to-growatt-inverter-data/page/2/

**Comment by ealse** [comment]
I updated and changed this repository with code from @jpvdm1 and it should work now and it includes also methods for a storage inverter device. But it needs some testing. If it works also for you I can update the current nuget packages with a new version. And if you need it in the future, you can now also change the urls if you need to.

@jpvdm1 can you also test the latest code with your account?

**Comment by jpvdm1** [comment]
@ealse works fine for me.

**Comment by panuoksala** [comment]
Yeah able to login again thanks. How do I get plantId ?

**Comment by panuoksala** [comment]
GetPlantDetailDayData seems to return empty data set for all the days, @jpvdm1 does your work?

**Comment by ealse** [comment]
It returns the amount of energy generated by the solar panels for each 5 minutes of the given day. My solar panels started at 6am. This means that the first 72 records are null. (6 hours / 5 minutes = 72) 

But I will improve the console example for extra clarity.

**Comment by jpvdm1** [comment]
I think this is where the difference in device types comes in as I don't get any data for GetPlantDetailDayData.
For any time based data I use the Chart endpoints like:
- GetStorageBatChartData
- GetStorageEnergyDayChart

There are additional Chart and Fault Log endpoints on the Growatt REST API.
@ealse should we create a new issue to add these?

**Comment by panuoksala** [comment]
StorageEnergyDayChart is for batteries?

**Comment by jpvdm1** [comment]
Example output for StorageEnergyDayChart:

``----- Energy Trend -------``
``---- Charge 11.5 kWh : Solar Storage 11.2 kWh / Grid Storage 0.3 kWh``
``---- Load Consumption 32.2 kWh : Inverter 0 kWh / Inverter 32.2 kWh``
``- 2022-08-01 00:00 : Solar 0 W / Imported from Grid 548 W / Load Consumption 524 W``
``- 2022-08-01 00:05 : Solar 0 W / Imported from Grid 517 W / Load Consumption 543 W``
``- 2022-08-01 00:10 : Solar 0 W / Imported from Grid 660 W / Load Consumption 661 W``
``- 2022-08-01 00:15 : Solar 0 W / Imported from Grid 779 W / Load Consumption 759 W``
``- 2022-08-01 00:20 : Solar 0 W / Imported from Grid 760 W / Load Consumption 729 W``
``- 2022-08-01 00:25 : Solar 0 W / Imported from Grid 879 W / Load Consumption 889 W``
``- 2022-08-01 00:30 : Solar 0 W / Imported from Grid 850 W / Load Consumption 890 W``

**Comment by jpvdm1** [comment]
So I'm using this library for the following:

- Telegram alerts for when there isn't any power from the grid (load shedding / substation issues etc)
- Telegram alerts for current load / overload

Thus I haven't really looked at the time based data as my use cases are pretty simple.

**Comment by panuoksala** [comment]
All the GetData methods are returning zero values to me. I had solar panels for three weeks now.

**Comment by ealse** [comment]
@panuoksala can you try the method GetPlantDetailDayChartData in:
https://github.com/ealse/GrowattApi/tree/feature/Plant-Detail-Day-Chart-Data

And otherwise you have to login on https://server.growatt.com/index and look get the information from the network tab.
But you can first try the method I added to the feature.

**Comment by panuoksala** [comment]
Yes that did the trick and it is now returning data. Ty.

**Comment by ealse** [comment]
Ok great, I will add also the other methods for year month etc later this week.

**Comment by ealse** [comment]
Added the other methods as named, which are also updated in the console example.
And released version 0.2.0 to Nuget
