### ISSUE TITLE
does it need any token or special access or just growwatt api

### ISSUE THREAD

**Issue by xtendtech** [ealse/GrowattApi#6]
I see some documentation for token . I am not sure if we need to get it. There is no dev support anywhere  in their site.
Only sales and service. So i am not sure if we ned to get some token or special permission to call growatt api

**Comment by ealse** [comment]
Growatt has not officially released a public API. That is the reason there is no API token available and you need to login with your own user account. See also [readme](https://github.com/ealse/GrowattApi#warning)
